paths:
  uploads: assets/images
  static: ''

collections_config:
  pages:
    path: ''
    name: 'خالد'
    icon: 10mp
  admin:
    path: admin
    icon: ad
  gallery:
    path: gallery
    icon: allergy

nav:
  - name: "خالد"
    collection: "pages"
  - name: "معرض الصور"
    collection: "gallery"
  - name: "مسؤول"
    collection: "admin"

editor:
  default_path: ''

timezone: Asia/Aden

markdown:
  engine: commonmark
  options:
    html: true
