site_url: https://lamasatfoundation-cell.github.io/lamasat-foundation.github.io/
backend:
  name: github
  repo: Lamasatfoundation-cell/lamasat-foundation.github.io
  branch: main

media_folder: "assets/images"
public_folder: "assets/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
