backend:
  name: github
  repo: lamasatfoundation-cell/lamasat-foundation.github.io
  branch: main
  base_url: https://lamasat-foundation-cells-projects.vercel.app/api
local_backend: true

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "public/index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
